
# 训练配置
training:
  # 输出目录
  output_dir: "./outputs"
  # 是否覆盖输出目录
  overwrite_output_dir: true
  # 训练轮数
  num_train_epochs: 3
  # 每个设备的批次大小
  per_device_train_batch_size: 4
  # 每个设备的评估批次大小
  per_device_eval_batch_size: 4
  # 梯度累积步数
  gradient_accumulation_steps: 4
  # 学习率
  learning_rate: 2e-5
  # 权重衰减
  weight_decay: 0.01
  # 学习率调度器
  lr_scheduler_type: "cosine"
  # 预热步数比例
  warmup_ratio: 0.1
  # 日志记录步数
  logging_steps: 10
  # 评估步数
  eval_steps: 100
  # 保存步数
  save_steps: 100
  # 最大保存检查点数量
  save_total_limit: 3

# 数据配置
data:
  # 训练数据路径
  train_file: "data/processed/train.json"
  # 验证数据路径
  validation_file: "data/processed/validation.json"
  # 最大训练样本数
  max_train_samples: null
  # 最大验证样本数
  max_eval_samples: null
  # 数据预处理
  preprocessing:
    # 最大源序列长度
    max_source_length: 512
    # 最大目标序列长度
    max_target_length: 512
    # 填充到最大长度
    pad_to_max_length: true
    # 数据加载时的并行进程数
    num_workers: 4

# 优化器配置
optimizer:
  # 优化器类型
  name: "adamw_torch"
  # 是否使用8位优化器
  use_8bit: false
  # 梯度裁剪
  max_grad_norm: 1.0

# 混合精度训练配置
mixed_precision:
  # 是否启用混合精度训练
  enabled: true
  # 混合精度类型
  dtype: "float16"  # 或 "bfloat16"

# 分布式训练配置
distributed:
  # 是否启用分布式训练
  enabled: false
  # 后端
  backend: "nccl"

